---
title: "Лабораторная работа №2"
author: Газиков Р.А.
format:
    md:
        output-file: readme.md
    
editor: visual
---

## Цель Работы

1.  Изучить возможности технологии Yandex DataLens для визуального анализа структурированных наборов данных
2.  Получить навыки визуализации данных для последующего анализа с помощью сервисов Yandex Cloud
3.  Получить навыки создания решений мониторинга/SIEM на базе облачных продуктов и открытых программных решений
4.  Закрепить практические навыки использования SQL для анализа данных сетевой активности в сегментированной корпоративной сети

## Ход работы

## Задание 1

Представить в виде круговой диаграммы соотношение внешнего и внутреннего сетевого трафика

```         
IF (([src] LIKE '12.%' or [src] LIKE '13.%' or [src] LIKE '14.%') and ([dst] LIKE '12.%' or [dst] LIKE '13.%' or [dst] LIKE '14.%'))
    THEN 'Внутренний Трафик'
ELSE
    'Внешний Трафик'
END
```

<image src = "images\a.jpg">

## Задание 2

Представить в виде столбчатой диаграммы соотношение входящего и исходящего трафика из внутреннего сетвого сегмента.

```         
IF (([src] like '12.%' or [src] like '13.%' or [src] like '14.%') and ([dst] not like '12.%' and [dst] not like '13.%' and [dst] not like '14.%'))
    THEN 'Исходящий трафик'
ELSEIF (([dst] like '12.%' or [dst] like '13.%' or [dst] like '14.%') and ([src] not like '12.%' and [src] not like '13.%' and [src] not like '14.%'))
    THEN 'Входящий трафик'
ELSE
    NULL
END
```

<image src = "images\b1.jpg">

## Задание 3

Построить график активности (линейная диаграмма) объема трафика во времени.

<image src = "images\c.jpg">

```{r}
a <- 1
a
```

## Задание 4

### Все построенные графики вывести в виде единого дашборда в Yandex DataLens.
<image src = "images\d.jpg">

## Вывод

Изучили возможности Yandex DataQuery и закрепили навыки построения дашбордов и визуализации сетевой активности с помощью DataLens.
